#https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"

# if you choose `ruff-lsp`
[language-server.ruff]
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

# [[language]]
# name = "python"
# language-servers = [ "pyright" ]
# auto-format = true


#https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---ruff
# [language-server.ruff-lsp]
# command = "ruff-lsp"
# [[language]]
# name = "python"
# language-servers = [ "ruff-lsp" ]

# [[language]]
# name = "python"
# language-servers = [ "ruff" ]
# auto-format = true
# [language-server.ruff]
# command = "ruff"
# args = ["server"]
